Feature/doc 11675 extend localization pr check with additional rules/dev
readdle/RD2SwiftLintConfig pull request #7
Opened 2024-04-15 14:13 UTC by ostrovdi

__Ticket link__

[DOC-11675](https://readdle-j.atlassian.net/browse/DOC-11675)

__PR description__
Part of pr [5967](https://github.com/readdle/rd2/pull/5967).

P.S. Pr will be merged in main only after discussion with PE team.

2024-04-15 15:27 UTC, salpieiev reviewed
Почекаю на фінальні зміни

2024-04-16 11:04 UTC, salpieiev commented on swiftlint_base.yml
> +    regex: 'NSLocalizedString\(\s*"[^"\n]*\\"[^"\n]*'
А якщо після `NSLocalizedString(` йде розрив строки, воно точно працює? Ато у мене є сумніви

2024-04-16 11:16 UTC, ostrovdi commented on swiftlint_base.yml
> +    regex: 'NSLocalizedString\(\s*"[^"\n]*\\"[^"\n]*'
Так, цей кейс покритий через \s* - any whitespace character.

2024-04-16 11:24 UTC, salpieiev commented on swiftlint_base.yml
> +    regex: 'NSLocalizedString\(\s*"[^"\n]*\\"[^"\n]*'
Те що воно працює в теорії я тут розумію, питання цікавить чи працює воно на практиці? Я не знаю в якому вигляді SwiftLint згодовує інпут для цих регулярок. Тому і перепитав про всяк випадок

2024-04-16 11:25 UTC, ostrovdi commented on swiftlint_base.yml
> +    regex: 'NSLocalizedString\(\s*"[^"\n]*\\"[^"\n]*'
На практиці теж перевірив) і з пробілами і з новими рядками працює.

2024-04-16 14:00 UTC, salpieiev approved these changes

2024-04-16 14:02 UTC, lyeskin approved these changes

2024-04-17 08:56 UTC, ostrovdi commented
@apodrugin, @aishchenko-readdle подивіться будь ласка ці правила оскільки їх впровадження вплине і на ваші проєкти. Головна ідея завдання це не допускати появи прямих лапок чи апострофа в рядках а використовувати замість них друкарські символи.

"quotes" -> “quotes”
backticks ` or single quote ' -> typographic apostrophe ’

2024-04-17 09:15 UTC, aishchenko-readdle commented
> @apodrugin, @aishchenko-readdle подивіться будь ласка ці правила оскільки їх впровадження вплине і на ваші проєкти. Головна ідея завдання це не допускати появи прямих лапок чи апострофа в рядках а використовувати замість них друкарські символи.
> 
> "quotes" -> “quotes” backticks ` or single quote ' -> typographic apostrophe ’

В PEM 40 ошибок.
Правило можно замерживать после починки всех срабатываний.

2024-04-17 09:32 UTC, ostrovdi commented
> > @apodrugin, @aishchenko-readdle подивіться будь ласка ці правила оскільки їх впровадження вплине і на ваші проєкти. Головна ідея завдання це не допускати появи прямих лапок чи апострофа в рядках а використовувати замість них друкарські символи.
> > "quotes" -> “quotes” backticks ` or single quote ' -> typographic apostrophe ’
> 
> В PEM 40 ошибок. Правило можно замерживать после починки всех срабатываний.

Коли орієнтовно ви б могли це зробити?

2024-04-17 09:48 UTC, aishchenko-readdle commented
> > > @apodrugin, @aishchenko-readdle подивіться будь ласка ці правила оскільки їх впровадження вплине і на ваші проєкти. Головна ідея завдання це не допускати появи прямих лапок чи апострофа в рядках а використовувати замість них друкарські символи.
> > > "quotes" -> “quotes” backticks ` or single quote ' -> typographic apostrophe ’
> > 
> > 
> > В PEM 40 ошибок. Правило можно замерживать после починки всех срабатываний.
> 
> Коли орієнтовно ви б могли це зробити?

Наступна неділя.

2024-04-17 10:11 UTC, aishchenko-readdle requested changes
Запрашиваю более детальный коммент по тому, какие символы должны вставляться.

2024-04-17 10:26 UTC, ostrovdi commented on swiftlint_base.yml
> +    #special cases - https://support.apple.com/uk-ua/guide/applestyleguide/q-apsg38496e66/1.0/web/1.0#apd29c9f643d5434
Можливо тоді вже так?

```
# Use curly quotation marks(”) (Option-Shift-Left Bracket) except units of measure and code font.
# Use double prime symbol(˝) (Option-Shift-G) for inches and prime symbol (´) (Option-Shift-E) for feet.
# https://support.apple.com/uk-ua/guide/applestyleguide/q-apsg38496e66/1.0/web/1.0#apd29c9f643d5434
```

2024-04-17 10:34 UTC, aishchenko-readdle approved these changes
Дякую, виглядає добре.

2024-04-17 16:48 UTC, aishchenko-readdle commented
> > > > @apodrugin, @aishchenko-readdle подивіться будь ласка ці правила оскільки їх впровадження вплине і на ваші проєкти. Головна ідея завдання це не допускати появи прямих лапок чи апострофа в рядках а використовувати замість них друкарські символи.
> > > > "quotes" -> “quotes” backticks ` or single quote ' -> typographic apostrophe ’
> > > 
> > > 
> > > В PEM 40 ошибок. Правило можно замерживать после починки всех срабатываний.
> > 
> > 
> > Коли орієнтовно ви б могли це зробити?
> 
> Наступна неділя.

Зявилася думка що ви не блочите PE Mac команді нічного.
Ми поки використовуємо `swiftlint_pem.yml` конфігурацію.
Зараз вона не залежить від `swiftlint_base.yml`, але ми в майбутньому зробимо наслідування від цієї.

Тому уточніть у PE iOS команди і якщо для них все ок - можете мержити.

2024-04-18 08:25 UTC, apodrugin requested changes
Є декілька проблем:
1. Ці регулярки не враховують локалізацію інтентів (див. скрипт у рд2  grep_intents_strings)
2. Якщо цей ПР замерджити на мейн, то нам прилетить несподівана зайва робота. Тільки у РД2 у нас біля 10 помилок на цю тему. Раніше ми працювали по схемі що оновлення правил робилось в кожній репі з свіфт лінт окремо. Це дозволяло отримувати оновлені правила ліниво і команда могла пофіксити проблеми при мерджах, а не в середині свого робочого циклу.

2024-04-18 09:18 UTC, pastey commented
Чому б не поєднати цю роботу із переходом на локальний конфіг в s7?
Тоді вона не буде нікого блочити. Перейти на локальний конфіг не виглядає як rocket science, як на мене.
(я знаю, що рандом обрав для цієї задачі PEM)

2024-04-19 15:05 UTC, ostrovdi commented
@apodrugin фікс з врахуванням локалізації інтентів додав.
Ідею @pastey з переходом на s7 в рамках цієї задачі взяв в роботу, тому пункт 2 також мав би бути вирішений.

2024-04-22 11:54 UTC, apodrugin approved these changes

2024-05-24 15:05 UTC, merged